{{- if .Values.createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: streamlit
  labels:
    name: streamlit
    istio-injection: disabled
{{- end }}

#---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#    name: allow-all
#    namespace: streamlit
#spec:
#    rules:
#      - {}
