{{- if .Values.secrets.gitSecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.gitSecret.name }}
  namespace: streamlit
stringData:
  username: {{ .Values.secrets.gitSecret.username }}
  password: {{ .Values.secrets.gitSecret.password }}
{{- end }}
{{- if .Values.secrets.gitDeployKey.create }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secrets.gitDeployKey.name }}
    namespace: streamlit
stringData:
  ssh: {{ .Values.secrets.gitDeployKey.ssh }}
  known_hosts: {{ .Values.secrets.gitDeployKey.known_hosts }}
{{- end }}
